### ISSUE TITLE
Space Travelers Project Kanban Team

### ISSUE THREAD

**Issue by yaredtekle022** [RileyManda/space-travelers-hub#21]
[Kanban Project](https://github.com/RileyManda/space-travelers-hub/projects/1)

Team members

 @yaredtekle022 

@RileyManda

**Comment by algerina** [comment]
Hi team,

Great job so far!  However you should have 17 issues as per the [template ](https://github.com/microverseinc/curriculum-react-redux/projects/1), you just have to remove the issues assigns to team 3 member. I noticed too that you don't have a group tasks.



## CHANGES REQUIRED:muscle::clap:

Check the comments under the review.


<img src="https://media4.giphy.com/media/neUaH5fz6ZpefE2KBP/giphy.gif"/>
 
 ## Optional suggestions

 - Please check the comment under the review.

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread and tag me @algerina if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)
___
_If anything seems to be unclear to you, reach out and ask anything by commenting on this Pull Request and mention me as [Algerina](https://github.com/algerina), I will receive a notification and will respond._

[GitHub](https://github.com/algerina) | [LinkedIn](https://linkedin.com/in/amel-khiri) | [Twitter](https://twitter.com/AmelQahwadji)

_Reviewed by [Amel Khiri ](https://github.com/algerina)_

**Comment by Olamarx** [comment]
Hi Team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Kanban board usage ✔️

 ## Required Changes ♻️
_Check the comments under the review._
- As the previous reviewer noted, your card should total 17 but what you have currently is far more than that.
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by RileyManda** [comment]
We have implemented the changes as suggested by the preview reviewer and ensured there are 17 cards in our [Kanban](https://github.com/RileyManda/space-travelers-hub/projects/2) for the 2 team member pairing.

Please kindly review our implementation and suggest changes.:

<img width="371" alt="Screen Shot 2023-07-31 at 2 04 54 PM" src="https://github.com/RileyManda/space-travelers-hub/assets/37291194/9a48909f-05c6-48a9-b962-07a06728b713">

Thank you

**Comment by Olamarx** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Good use of Kanban board ✔️
## Optional suggestions
- I noticed you closed the previous board, you should have just edited it or the link you provided in this issue description.
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
